### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by Mikanoshi** [Stericson/RootTools#43]
I'm running root check and then a command from com.android.internal.policy.impl.PhoneWindowManager.systemBooted().
I works fine for me and numerous other users, but some have this error that causes bootloop:
```
W/Watchdog(28990): *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in handler on ui thread (android.ui)
D/Process (28990): killProcess, pid=28990
W/Watchdog(28990): ui thread stack trace:
W/Watchdog(28990):     at java.lang.Object.wait(Native Method)
D/Process (28990): com.android.server.Watchdog.run:581 <bottom of call stack> <bottom of call stack>
W/Watchdog(28990):     at java.lang.Thread.join(Thread.java:786)
W/Watchdog(28990):     at java.lang.Thread.join(Thread.java:744)
W/Watchdog(28990):     at com.stericson.RootShell.execution.Shell.<init>(Shell.java:187)
W/Watchdog(28990):     at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:848)
W/Watchdog(28990):     at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:834)
W/Watchdog(28990):     at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:826)
W/Watchdog(28990):     at com.stericson.RootShell.RootShell.isAccessGiven(RootShell.java:372)
W/Watchdog(28990):     at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:616)
W/Watchdog(28990):     at com.sensetoolbox.six.mods.WakeGesturesMods$10$1.run(WakeGesturesMods.java:637)
W/Watchdog(28990):     at android.os.Handler.handleCallback(Handler.java:739)
W/Watchdog(28990):     at android.os.Handler.dispatchMessage(Handler.java:95)
W/Watchdog(28990):     at android.os.Looper.loop(Looper.java:155)
W/Watchdog(28990):     at android.os.HandlerThread.run(HandlerThread.java:61)
W/Watchdog(28990):     at com.android.server.ServiceThread.run(ServiceThread.java:46)
W/Watchdog(28990): *** GOODBYE!
```
Any way to fix this or is it too early on boot and only delay will help?

**Comment by Allan-Nava** [comment]
With android 7.1.2 I got the reboot every 5 minutes, it's normal?

**Comment by JcChimjj** [comment]
#43

**Comment by JcChimjj** [comment]
#43

**Comment by Stericson** [comment]
Taking a wild stab at this, but I imagine this is caused by SELinux and you need to either run these commands with a different Context or disable SELinux.
