### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DamonChen117** [Stericson/RootTools#86]
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.stericson.RootTools.internal.RootToolsInternalMethods$6.commandOutput(RootToolsInternalMethods.java:675)
        at com.stericson.RootShell.execution.Command.output(Command.java:288)
        at com.stericson.RootShell.execution.Shell$3.run(Shell.java:693)
        at java.lang.Thread.run(Thread.java:818)

**Comment by JcChimjj** [comment]
#86

**Comment by beckerichmika** [comment]
This seems to be an error coming from your code itself. Do you have any array which are either uninitialized or size 0?
